USE HumaneSociety;
GO

DROP PROCEDURE IF EXISTS INSERTVOLUNTEER;
DROP PROCEDURE IF EXISTS INSERTADOPTER;
DROP PROCEDURE IF EXISTS InsertPetOwner;
DROP PROCEDURE IF EXISTS INSERTVeterinarian;
DROP PROCEDURE IF EXISTS INSERTPerson;
GO