REVOKE SELECT, INSERT, UPDATE, DELETE ON SCHEMA::shelter FROM HumaneSociety_Staff;
REVOKE SELECT, INSERT, UPDATE, DELETE ON SCHEMA::people FROM HumaneSociety_Staff;
REVOKE SELECT, INSERT, UPDATE, DELETE ON SCHEMA::medical FROM HumaneSociety_Staff;
REVOKE SELECT ON SCHEMA::audit FROM HumaneSociety_Staff;