GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::shelter TO HumaneSociety_Staff;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::people TO HumaneSociety_Staff;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::medical TO HumaneSociety_Staff;
GRANT SELECT ON SCHEMA::audit TO HumaneSociety_Staff;