export default function Section2(){
    return(
        <main className = "main-section3">
          <img src = "/src/assets/ccweb_orig.jpg" />
          <header className ="headings3">
            <h3>The evening of Saturday, April 5 will come alive under the big top for Canine Carnival:
                benefiting the medical needs of the dogs for the Humane Society of Northwest Louisiana. 
                Guests will experience a night of fantasy and sideshow fun exploring creative concessions, enjoying immersive entertainment, 
                and taking chances at wonderful items in our silent auction. All proceeds generated by Canine Carnival will go directly to 
                funding the medical expenses for dogs under the care of the Humane Society of Northwest Louisiana. We hope you will join us to underwrite this night of revelry!
            </h3>
            <h3> Tickets are $125 each</h3>    
            <h3> Dress attire - cocktail, formal or carnival themed costome</h3>
          </header>
                



            
        </main>
    )
}